smartresize/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^smartrez/', include('smartrez.urls'))
]

smartrez/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'smartrez'
urlpatterns = [
                  url(r'^$', views.index, name='index'),
                  # normal regex handling by django of urls to views, uses strings as args cause queries shouldn't be
                  #  unique, a pizza query made again will redirect to the old pizza query with new images added if
                  # available
                  url(r'^(?P<query_term>[\w\-]+)/$', views.results, name='results'),
                  url(r'^(?P<query_term>[\w\-]+)/gallery/$', views.gallery, name='gallery'),
                  url(r'^(?P<query_term>[\w\-]+)/gallery_l/$', views.gallery_l, name='gallery_l'),
                  url(r'^q_create$', views.q_create, name='q_create'),
                  url(r'^(?P<query_term>[\w\-]+)/resize/$', views.resize, name='resize'),
                  url(r'^(?P<query_term>[\w\-]+)/restore/$', views.restore, name='restore'),
                  url(r'^(?P<query_term>[\w\-]+)/delete/$', views.delete, name='delete'),
                  url(r'^(?P<query_term>[\w\-]+)/upload/$', views.upload, name='upload')
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# handles serving of media files from smartresize/media/q_results, so in the webpage,
# /smartrez/media/ is actually .../smartresize/media/q_results/

smartrez/models.py
from django.db import models


# a searchquery view to hold the name of a query
class SearchQuery(models.Model):
    term = models.CharField(max_length = 200)


# holds images for each search query, utilises foreign key to maintain images for each query
class Img(models.Model):
    # self explanatory field names
    search_query = models.ForeignKey(SearchQuery, on_delete=models.CASCADE)
    img_url = models.CharField(max_length=200)
    thumb_url = models.CharField(max_length=200)
    uses = models.IntegerField(default=0)
    img_id = models.IntegerField(default=0)

smartrez/forms.py
from django import forms

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=150)
    file = forms.FileField()

smartrez/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import SearchQuery, Img
from django.views import generic
from django.urls import reverse
from django.template import loader
from .titles import ImageScraper
from .forms import UploadFileForm
import subprocess
import threading
import itertools
import time
from django.conf import settings
import os
from os import listdir
from os.path import isfile, join
from os.path import basename
import zipfile
from shutil import copyfile


def zipmaker(filelist, query_term):  # zipmaker called on every image operation to keep zips ready for download
    ziph = zipfile.ZipFile(settings.MEDIA_ROOT + query_term + '/' + 'edited_' + query_term + '.zip', 'w',
                           zipfile.ZIP_DEFLATED)  # edited
    zipo = zipfile.ZipFile(settings.MEDIA_ROOT + query_term + '/' + 'original_' + query_term + '.zip', 'w',
                           zipfile.ZIP_DEFLATED)  # original
    for file in filelist:
        ziph.write(settings.MEDIA_ROOT + query_term + '/edited/' + file, basename(
            settings.MEDIA_ROOT + query_term + '/edited/' + file))  # using basename so server directories arent copied
        zipo.write(settings.MEDIA_ROOT + query_term + '/base/' + file,
                   basename(settings.MEDIA_ROOT + query_term + '/base/' + file))
    ziph.close()  # this stuff is to be put into a download view
    zipo.close()


def q_create(request):  # View is called from the first index page from the search button
    name = request.POST['term'].replace(' ', '_').lower()  # get search query from the POST request
    try:
        IS = ImageScraper()
        q = SearchQuery.objects.get(term=name)  # check if we already have this query searched in the database
        thumb_list, img_list, pixabay_id = IS.get_img(srch=request.POST['term'], type=request.POST[
            'type'])  # from imagescraper get images for this query
        for img, thumb, id in itertools.zip_longest(img_list, thumb_list, pixabay_id):
            try:
                k = q.img_set.get(img_id=id)  # check the database with pixabay_id to see if it exists
                k.delete()
                q.img_set.create(img_url=img, thumb_url=thumb,
                                 img_id=id)
                # if that errored, image didnt exist so create an entry for this supposedly newly added image on pixabay
            except:
                q.img_set.create(img_url=img, thumb_url=thumb,
                                 img_id=id)
                # if that errored, image didnt exist so create an entry for this supposedly newly added image on pixabay
    except:  # in case its a new query, try would error so we come to except
        q = SearchQuery(term=name)  # new searchquery with this new query name
        q.save()
        IS = ImageScraper()
        thumb_list, img_list, pixabay_id = IS.get_img(srch=request.POST['term'],
                                                      type=request.POST['type'])  # get images from pixabay
        for thumb, img, id in itertools.zip_longest(thumb_list, img_list, pixabay_id):
            q.img_set.create(img_url=img, thumb_url=thumb,
                             img_id=id)  # create img objects/database entries for images of this query
    return HttpResponseRedirect(reverse('smartrez:results', args=(
    name,)))  # reverse smartrez:results with name as args and redirect to page, urls are namespaced with app name


def index(request):  # view for the index page
    querylist = []
    for query in SearchQuery.objects.all():
        querylist.append(query.term)  # load existing queries for the gallery view
    template = loader.get_template('smartrez/index.html')
    context = {'querylist': querylist}
    return HttpResponse(template.render(context, request))


def results(request, query_term):  # results page view
    query = get_object_or_404(SearchQuery, term=query_term)  # get query
    template = loader.get_template(
        'smartrez/results.html')  # send query as context to the page, the page handles the rest
    context = {'query': query, 'query_name': query.term.replace('_', ' ')}
    return HttpResponse(template.render(context, request))


def smartcrop(width, height, query_term, file):  # function to run in threads to massively speed up operation time
    subprocess.run(['smartcrop --width %s --height %s "%s" "%s"' % (
    width, height, (settings.MEDIA_ROOT + query_term + '/edited/' + file),
    (settings.MEDIA_ROOT + query_term + '/edited/' + file))], shell=True)
    subprocess.run(['magick %s -compress JPEG -quality 80 %s' % (
    (settings.MEDIA_ROOT + query_term + '/edited/' + file), (settings.MEDIA_ROOT + query_term + '/edited/' + file))],
                   shell=True)


def restore(request, query_term):  # restore images from maintained base folder
    query = get_object_or_404(SearchQuery, term=query_term)
    restorefilestring = request.POST['restore']  # get the restore from the post request
    restorefilelist = restorefilestring.split(',')
    restorelist = restorefilelist[:-1]
    for file in restorelist:
        copyfile(settings.MEDIA_ROOT + '%s/base/%s' % (query_term, file),
                 settings.MEDIA_ROOT + '%s/edited/%s' % (query_term, file))
    template = loader.get_template('smartrez/gallery.html')
    filelist = [f for f in listdir(settings.MEDIA_ROOT + query_term + '/edited') if
                isfile(join(settings.MEDIA_ROOT + query_term + '/edited', f))]
    zipmaker(filelist, query_term)  # make zips
    context = {'editedzipname': 'edited_' + query_term + '.zip', 'originalzipname': 'original_' + query_term + '.zip',
               'query': query, 'filelist': filelist,
               'time': int(round(time.time()))}  # sending list of filenames back to gallery so it can load pictures
    return HttpResponse(template.render(context, request))


def delete(request, query_term):  # delete images from base and edited directory, permanent loss
    query = get_object_or_404(SearchQuery, term=query_term)
    restorefilestring = request.POST['delete']
    restorefilelist = restorefilestring.split(',')
    restorelist = restorefilelist[:-1]
    for file in restorelist:
        os.remove(settings.MEDIA_ROOT + '%s/base/%s' % (query_term, file))
        os.remove(settings.MEDIA_ROOT + '%s/edited/%s' % (query_term, file))
    template = loader.get_template('smartrez/gallery.html')
    filelist = [f for f in listdir(settings.MEDIA_ROOT + query_term + '/edited') if
                isfile(join(settings.MEDIA_ROOT + query_term + '/edited', f))]
    zipmaker(filelist, query_term)  # zips
    context = {'editedzipname': 'edited_' + query_term + '.zip', 'originalzipname': 'original_' + query_term + '.zip',
               'query': query, 'filelist': filelist,
               'time': int(round(time.time()))}  # sending list of filenames back to gallery so it can load pictures
    return HttpResponse(template.render(context, request))


def resize(request, query_term):  # resize function
    query = get_object_or_404(SearchQuery, term=query_term)  # get query
    filestring = request.POST['act_img']  # get their selected images from POST
    filelist = filestring.split(',')  # JS on the gallry page adds filename then a comma
    editlist = filelist[:-1]  # last comma is a stray comma so remove last entry resulting from strip
    filelist = [f for f in listdir(settings.MEDIA_ROOT + query_term + '/edited') if isfile(
        join(settings.MEDIA_ROOT + query_term + '/edited',
             f))]  # two directories, base and edited are maintained, editing will be handled in the edited folder, soon to add restoring base images into edited incase wrong operations
    real_imglist = []
    width = request.POST['width']
    height = request.POST[
        'height']  # take dimensions from the POST requests, soon to be put as optional as more image ops are added
    threaddict = {}
    for counter, file in enumerate(editlist):  # make and start threads
        threaddict[counter] = threading.Thread(target=smartcrop, args=(width, height, query.term, file))
        threaddict[counter].daemon = True
        threaddict[counter].start()
    for key in threaddict.keys():  # wait for all threads to finish
        threaddict[key].join()
    print(filelist)
    zipmaker(filelist, query_term)
    template = loader.get_template('smartrez/gallery.html')
    context = {'editedzipname': 'edited_' + query_term + '.zip', 'originalzipname': 'original_' + query_term + '.zip',
               'query': query, 'filelist': filelist,
               'time': int(round(time.time()))}  # sending list of filenames back to gallery so it can load pictures
    return HttpResponse(template.render(context, request))


def gallery(request,
            query_term):  # gallery view, all submit buttons post to this view, so each image in the actimg post gets its use no. increased, will be moved to download view
    query = get_object_or_404(SearchQuery, term=query_term)
    urlstring = request.POST['act_img']  # same as the act img in resize
    urllist = urlstring.split(',')
    urllist = urllist[:-1]
    real_imglist = []
    for url in urllist:
        q_obj = query.img_set.get(thumb_url=url)
        q_obj.uses += 1
        q_obj.save()
        real_imglist.append(q_obj.img_url)
    IS = ImageScraper()
    filelist = IS.save_imgs(urllist=real_imglist,
                            query_name=query.term)  # call the image downloader with your selected urls
    zipmaker(filelist, query_term)
    template = loader.get_template('smartrez/gallery.html')
    context = {'editedzipname': 'edited_' + query_term + '.zip', 'originalzipname': 'original_' + query_term + '.zip',

smartrez/templates/smartrez/gallery.html
<!DOCTYPE html>
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<style>
.modal {
    display: none; 
    position: fixed;
    z-index: 1;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    overflow: auto;
    background-color: rgb(0,0,0);
    background-color: rgba(0,0,0,0.4);
}
.modal-content {
    background-color: #fefefe;
    margin: 15% auto; 
    padding: 20px;
    border: 1px solid #888;
    width: 80%; 
}
.close {
    color: #aaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: black;
    text-decoration: none;
    cursor: pointer;
} 
html {
 padding: 5%;
 text-align: center;
}
.main.sel {
 border: 2px solid #99ff66 !important;
}
.main{
    margin: 25px !important;
    border: 2px solid #ccc !important;
    -webkit-transition: all 0.4s ease-in-out;
    transition: border 0.4s;
    display: inline-block !important;
    width: 200px !important;
}
.main:hover {
 border: 2px solid #99ff66 !important;
 -webkit-transition: all 0.4s ease-in-out;
 transition: border 0.4s;
}
.del.select {
 border: 2px solid #99ff66 !important;
}
.del{
    margin: 25px !important;
    border: 2px solid #ccc !important;
    -webkit-transition: all 0.4s ease-in-out;
    transition: border 0.4s;
    display: inline-block !important;
    width: 200px !important;
}
.del:hover {
 border: 2px solid #99ff66 !important;
 -webkit-transition: all 0.4s ease-in-out;
 transition: border 0.4s;
}
.image{
    height:150px !important;
    width:200px !important;
    z-index: 99 !important;
    float: left !important;
}
.check{
    float: right !important;
    z-index: 100 !important;
    margin: -150px 0px 0px !important;
    cursor: pointer;
    width: 15px !important;
    height: 15px !important;
}
</style>
</head>
<body>
{% for file in filelist %}
     <div class = "main">
         <img id="img{{forloop.counter}}" class ="image" src="/smartrez{{MEDIA_URL}}{{query.term}}/edited/{{file}}?time={{time}}" alt="{{query.term}}_img_{{forloop.counter}}" value="{{file}}">
         <input type="checkbox" class="check" id="check{{forloop.counter}}"/>
     </div>
{% endfor %}
<br>	
<form action="{% url 'smartrez:resize' query.term %}" method="post">
{% csrf_token %}
 <input type="hidden" name = "act_img" id="act_img" value="" size="40"/>
 <input type="text" name = "width" placeholder="Width"/> x <input type="text" name = "height" placeholder="Height"/>
 <input id="sub" type="submit" value="Resize" class="btn btn-success">
</form>
<form action="{% url 'smartrez:restore' query.term %}" method = "post">
{% csrf_token %}
<input type="hidden" name = "restore" id="restore" value="" size="40"/>
<input id="restorebut" type="submit" value="Restore selected images from backup" class="btn btn-info">
</form>
<div class="modal" id="myModal">
<div class="modal-content">
    <span class="close">&times;</span>
{% for file in filelist %}
     <div class = "del">
         <img id="img{{forloop.counter}}" class ="image" src="/smartrez{{MEDIA_URL}}{{query.term}}/edited/{{file}}?time={{time}}" alt="{{query.term}}_img_{{forloop.counter}}" value="{{file}}">
         <input type="checkbox" class="check" id="check{{forloop.counter}}"/>
     </div>
{% endfor %}
<form action="{% url 'smartrez:delete' query.term %}" method = "post">
{% csrf_token %}
<input type="hidden" name = "delete" id="delete" value="" size="40"/>
<input id="deletebut" type="submit" value="Delete selected images" class="btn btn-danger">
</form>
</div>
</div>
<form enctype="multipart/form-data" action="{% url 'smartrez:upload' query.term %}" method="post">
{% csrf_token %}
<input name="file" id="fileup"type="file"/>
<input id="up" type="submit" value="Upload" class="btn btn-success">
<label for="#fileup">Upload an image</label>
</form>

<br>
<button id="myBtn" class="btn btn-danger">Delete images</button>

<br>
<a href="/smartrez/"><button id="myBtn" class="btn btn-warning">Go Home</button></a>
<br>
<h3>Download images from last operation</h3>
<br>
<a href="/smartrez{{MEDIA_URL}}{{query.term}}/{{editedzipname}}" download="smartrez_{{editedzipname}}"><button type="button" class="btn btn-success">Download Edited</button></a>
<br>
<a href="/smartrez{{MEDIA_URL}}{{query.term}}/{{originalzipname}}" download="smartrez_{{originalzipname}}"><button type="button" class="btn btn-success">Download Original</button></a>
<script>
$(document).ready(function(){
  console.log('ready');
  $('.main img').each(function() {
    $(this).parent().addClass('sel');
    $(this).parent().find('.check').prop('checked', true);
});
var modal = document.getElementById('myModal');
var btn = document.getElementById("myBtn");
var span = document.getElementsByClassName("close")[0];
btn.onclick = function() {
    modal.style.display = "block";
}
span.onclick = function() {
    modal.style.display = "none";
}
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
} 
  $('.main img').on('click', function(){
    if($(this).parent().hasClass('sel') == true) {
     $(this).parent().removeClass('sel')
     $(this).parent().find('.check').prop('checked', false);
    }
    else {
    $(this).parent().addClass('sel');
    $(this).parent().find('.check').prop('checked', true);
    console.log('log');
    }
  });
  $('.del img').on('click', function(){
    if($(this).parent().hasClass('select') == true) {
     $(this).parent().removeClass('select')
     $(this).parent().find('.check').prop('checked', false);
    }
    else {
    $(this).parent().addClass('select');
    $(this).parent().find('.check').prop('checked', true);
    console.log('log');
    }
  });
$('#sub').on('click', function() {
   $('.main img').each(function() {
    console.log($(this).attr('src'));
    if($(this).parent().hasClass('sel') == true) {
    var prevact = $('#act_img').val();
    $('#act_img').val(prevact + $(this).attr('value') + ',');
   }
   console.log($('#act_img').val());
});
});
$('#restorebut').on('click', function() {
   $('.main img').each(function() {
    console.log($(this).attr('src'));
    if($(this).parent().hasClass('sel') == true) {
    var prevact = $('#restore').val();
    $('#restore').val(prevact + $(this).attr('value') + ',');
   }
   });
   });
$('#deletebut').on('click', function() {
   $('.del img').each(function() {
    console.log($(this).attr('src'));
    if($(this).parent().hasClass('select') == true) {
    var prevact = $('#delete').val();
    $('#delete').val(prevact + $(this).attr('value') + ',');
   }
   });
   });
$('#downloadbut').on('click', function() {
   $('.main img').each(function() {
    console.log($(this).attr('src'));
    if($(this).parent().hasClass('sel') == true) {
    var prevact = $('#download').val();
    $('#download').val(prevact + $(this).attr('value') + ',');
   }
   });
   });
});
</script>
</body>
</html>

smartrez/templates/smartrez/index.html
<head>
<title>Smartrez</title>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<style>
.wrap {
 text-align: center;
}
</style>
</head>
<body>
<div class="container">
<div class="row">
<div ng-view class="col-xs-5"></div>
<div ng-view class="col-xs-7 content">
<h1>Enter Term</h1>
<form action="{% url 'smartrez:q_create' %}", method="post">
{% csrf_token %}
<input type="textbox" name="term" id="term_1"/><br><br>
</div>
</div>
<div class="row">
<div ng-view class="col-xs-4 content"></div>
<div ng-view class="col-xs-3 content">
<h3>Type:</h3>
<div class='opt'>
<input type="radio" name="type" id="all" value="all" />
<label for="#all">All</label></div>
<div class='opt'>
<input type="radio" name="type" id="photo" value = "photo"/>
<label for="#photo">Photo</label></div>
<div class='opt'>
<input type="radio" name="type" id="illustration" value= "illustration"/>
<label for="#illustration">Illustration</label></div>
<div class='opt'>
<input type="radio" name="type" id="vector" value= "vector"/>
<label for="#vector">Vector</label></div>
</div>
<div ng-view class="col-xs-3">
<input type="submit" value="Search" class="btn btn-info">
</div>
</div>
</form>
<div ng-view class="col-xs-2"></div>
</div>
<div class="row">
<div ng-view class="col-xs-5"></div>
<div ng-view class="col-xs-5">
<h1>Gallery</h1>
<form id = "gal" action="">
{% for query in querylist %}
<div class='galopt'>
<input type="radio" name="query" id="gallery{{forloop.counter}}" value="{{query}}" />
<label for="#gallery{{forloop.counter}}">{{query}}</label></div>
{% endfor %}
</div>
</div>
<br>
<br>
<div class="row">
<div ng-view class="col-xs-5"></div>
<div ng-view class="col-xs-4">
<input id="galsub" type="submit" value="Open Gallery" class="btn btn-info">
</div>
<div ng-view class="col-xs-4"></div>
</form>
</div>
</body>
<script>
$(document).ready(function(){
 $('.opt label').on('click', function(){
  $(this).parent().find("input[name='type']").prop('checked', true)
});
 $('.galopt label').on('click', function(){ //convenience JS so you can click on the name and just expect the radio button to get selected too cause why not, but yeah it makes it easier
  $(this).parent().find("input[name='query']").prop('checked', true);
  $('#gal').attr('action', '/smartrez/' + $(this).parent().find("input[name='query']").val() + '/gallery_l'); //now for the submit button for gallery to post something, it should know where to post, the action is determined by which radio button is selected
});
$('#gal input').on('click', function() {
  $('#gal').attr('action', '/smartrez/' + $(this).val() + '/gallery_l'); //same thing but if you actually click the radio button instead of name
});
});
</script>

smartrez/templates/smartrez/resized.html
<head>
<title>Resized Image</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
.wrap {
 text-align: center;
}
.button {
  position: absolute;
  top: 50%;
 }
</style>
</head>
<body>
<div class="wrap">
<a href="/smartrez{{MEDIA_URL}}{{query.term}}/{{editedzipname}}" download="smartrez_{{editedzipname}}"><button type="button">Download Edited</button></a>
<br>
<a href="/smartrez{{MEDIA_URL}}{{query.term}}/{{orginalzipname}}" download="smartrez_{{originalzipname}}"><button type="button">Download Original</button></a>
<br>
<a href="/smartrez/{{query.term}}/gallery_l"><button type="button">Go back to {{query.term}} gallery</button></a>
</div>
</body>

smartrez/templates/smartrez/results.html
<!DOCTYPE html>
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<style>
html {
 padding: 5%;
 text-align: center;
}
.main.sel {
 border: 2px solid #99ff66;
}
.main{
    margin: 25px;
    border: 2px solid #ccc;
    -webkit-transition: all 0.4s ease-in-out;
    transition: border 0.4s;
    display: inline-block;
    width: 200px;
}
.main:hover {
 border: 2px solid #99ff66;
 -webkit-transition: all 0.4s ease-in-out;
 transition: border 0.4s;
}
.image{
    height:150px;
    width:200px;
    z-index: 99;
    float: left;
}
.check{
    float: right;
    z-index: 100;
    margin: -150px 0px 0px;
    cursor: pointer;
    width: 15px;
    height: 15px;
}
</style>
</head>
<body>
{% for choice in query.img_set.all %}
     <div class = "main">
         <img id="img{{forloop.counter}}" class ="image" src="{{choice.thumb_url}}" alt="{{query.term}}_img_{{forloop.counter}}">
         <input type="checkbox" class="check" id="check{{forloop.counter}}"/>
     </div>
{% endfor %}
<br>
<form action="{% url 'smartrez:gallery' query.term %}", method="post">
{% csrf_token %}
 <input type="hidden" name = "act_img" id="act_img" value="" size="40"/>
 <input id="sub" type="submit" value="Resize" class="btn btn-info">
</form>
</body>
<script>
$(document).ready(function(){
  $('.main img').on('click', function(){ //this is just for the sweet visuals, or well, usability/ clicking on image adds a glowing border class so you know its selected, also the checkmark
    if($(this).parent().hasClass('sel') == true) {
     $(this).parent().removeClass('sel')
     $(this).parent().find('.check').prop('checked', false)
    }
    else {
    $(this).parent().addClass('sel');
    $(this).parent().find('.check').prop('checked', true)
    console.log('log');
    }
  });

});
$('#sub').on('click', function() { //the main js function that makes it possible, when the submit button is clicked, all divs with the sel class have their urls added to a hidden field, this is posted to the gallery view again 
   $('.main img').each(function() {
    console.log($(this).attr('src'));
    if($(this).parent().hasClass('sel') == true) {
    var prevact = $('#act_img').val();
    $('#act_img').val(prevact + $(this).attr('src') + ',');
   }
   console.log($('#act_img').val()); //too fast to see this in console but yeah
});
});
</script>
</html>
